name: Test Docusaurus Site

on:
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build-test:
    name: Build Docusaurus Site for PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'  # Specify your Node.js version here

      - name: Install dependencies
        run: |
          npm ci  # Install dependencies (use `npm install` if you haven't configured package-lock.json)

      - name: Build Docusaurus site
        run: |
          npm run build  # Build the Docusaurus website

      - name: Create status check
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const status = context.payload.workflow_run.conclusion === 'success' ? 'success' : 'failure';
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.payload.pull_request.head.sha,
              state: status,
              context: 'Build Docusaurus Site',
              description: status === 'success' ? 'Build succeeded' : 'Build failed',
            });
